name: Auto build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: install ninja-build
      uses: seanmiddleditch/gha-setup-ninja@v6
    - name: install llvm
      uses: KyleMayes/install-llvm-action@v2.0.6
      with:
        version: 1.19.1.7

    - name: build
      run: ninja windows.ninja
